// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "./BigViewToken.sol";

contract BigViewTreasury is ReentrancyGuard {
    
    // --- State Variables ---
    BigViewToken public immutable bvwToken; // Your LST (stSTX equivalent)
    IERC20 public immutable cbETHToken;     // The Input Asset (STX equivalent)
    
    address public devWallet;
    address public majorPoolAddress; // Signer Node delegation address
    
    uint256 public totalMembersCount;
    uint256 public totalStakedcbETH;
    uint256 public totalRewardsPaid;

    // --- Real-time Native ETH Reward Tracking (Paid by Signers) ---
    uint256 public rewardPerTokenStored;
    mapping(address => uint256) public userRewardPerTokenPaid;
    mapping(address => uint256) public ethRewardsAccumulated;

    struct Member {
        bool isMember;
        uint256 cbEthAmount; // Tracks how much cbETH they locked up
    }
    
    struct CycleSnapshot {
    uint256 cycleId;
    uint256 totalYieldDistributed;
    uint256 timestamp;
}

CycleSnapshot[] public cycles;

    mapping(address => Member) public members;
    
    // --- Events ---
    event Staked(address indexed user, uint256 cbEthAmount, uint256 bvwMinted);
    event Withdrawn(address indexed user, uint256 bvwBurned, uint256 cbEthReturned);
    event EthRewardsClaimed(address indexed user, uint256 amount);

    // --- Errors ---
    error NotAuthorized();
    error NoStake();
    error TransferFailed();
    error InvalidAmount();
    error NothingToClaim();

    modifier updateReward(address account) {
        if (account != address(0)) {
            ethRewardsAccumulated[account] = earned(account);
            userRewardPerTokenPaid[account] = rewardPerTokenStored;
        }
        _;
    }

    constructor(address _bvwToken, address _cbETH, address _majorPool) {
        bvwToken = BigViewToken(_bvwToken);
        cbETHToken = IERC20(_cbETH);
        devWallet = msg.sender;
        majorPoolAddress = _majorPool;
    }

    function earned(address account) public view returns (uint256) {
        return ((members[account].cbEthAmount * (rewardPerTokenStored - userRewardPerTokenPaid[account])) / 1e18) + ethRewardsAccumulated[account];
    }

    /**
     * @notice Stake cbETH, get back liquid BVW tokens instantly 1:1
     */
    function stake(uint256 _amount) external nonReentrant updateReward(msg.sender) {
        if (_amount == 0) revert InvalidAmount();

        // 1. Pull cbETH from user's wallet into this Treasury
        bool success = cbETHToken.transferFrom(msg.sender, address(this), _amount);
        if (!success) revert TransferFailed();

        // 2. Manage Protocol Membership
        if (!members[msg.sender].isMember) {
            members[msg.sender].isMember = true;
            totalMembersCount += 1;
        }

        members[msg.sender].cbEthAmount += _amount;
        totalStakedcbETH += _amount;

        // 3. 90/10 Split routing of the collateral asset
        uint256 poolShare = (_amount * 90) / 100;
        uint256 devShare = _amount - poolShare;

        bool sendToPool = cbETHToken.transfer(majorPoolAddress, poolShare);
        bool sendToDev = cbETHToken.transfer(devWallet, devShare);
        if (!sendToPool || !sendToDev) revert TransferFailed();

        // 4. Mint the Liquid LST token straight back to the user's wallet
        bvwToken.mint(msg.sender, _amount);

        emit Staked(msg.sender, _amount, _amount);
    }

    /**
     * @notice Unstake: Burn your BVW to permissionlessly reclaim your underlying cbETH
     */
    function unstake(uint256 _bvwAmount) external nonReentrant updateReward(msg.sender) {
        if (_bvwAmount == 0 || members[msg.sender].cbEthAmount < _bvwAmount) revert InvalidAmount();

        // 1. Update accounting states
        members[msg.sender].cbEthAmount -= _bvwAmount;
        totalStakedcbETH -= _bvwAmount;

        // 2. Destroy the user's receipt LST tokens
        bvwToken.burn(msg.sender, _bvwAmount);

        // 3. Return the underlying cbETH collateral from the protocol vaults
        bool success = cbETHToken.transfer(msg.sender, _bvwAmount);
        if (!success) revert TransferFailed();

        emit Withdrawn(msg.sender, _bvwAmount, _bvwAmount);
    }

    /**
     * @notice Claim native ETH validation rewards generated by the Signers
     */
    function claimEthRewards() external nonReentrant updateReward(msg.sender) {
        uint256 reward = ethRewardsAccumulated[msg.sender];
        if (reward == 0) revert NothingToClaim();

        ethRewardsAccumulated[msg.sender] = 0;

        // Take a 5% protocol fee from the validation yield payout
        uint256 devFee = (reward * 5) / 100;
        
        uint256 userShare = reward - devFee;
        
        totalRewardsPaid += userShare;

        (bool feeSent, ) = devWallet.call{value: devFee}("");
        (bool userSent, ) = msg.sender.call{value: userShare}("");
        if (!feeSent || !userSent) revert TransferFailed();

        emit EthRewardsClaimed(msg.sender, userShare);
    }
    
    function getExchangeRate() external view returns (uint256) {
    // For now on testnet, return a fixed simulation rate
    // When you go to mainnet, you can replace this with a Chainlink price feed or live calculation!
    return 1050000000000000000; 
}

    /**
     * @notice Call this when Signer nodes send raw ETH yields back to the contract
     */
    receive() external payable updateReward(address(0)) {
        if (totalStakedcbETH == 0) revert NoStake();
        rewardPerTokenStored = rewardPerTokenStored + ((msg.value * 1e18) / totalStakedcbETH);
    }
}