/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface BigViewTreasuryInterface extends Interface {
    getFunction(nameOrSignature: "claimRewards" | "devWallet" | "getDashboardSummary" | "majorPoolAddress" | "members" | "rewardMember" | "setMajorPool" | "stakeAndDelegate" | "totalMembersCount" | "totalStakedAmount"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'claimRewards', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'devWallet', values?: undefined): string;
encodeFunctionData(functionFragment: 'getDashboardSummary', values?: undefined): string;
encodeFunctionData(functionFragment: 'majorPoolAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'members', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'rewardMember', values: [AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'setMajorPool', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'stakeAndDelegate', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalMembersCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalStakedAmount', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'claimRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'devWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDashboardSummary', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'majorPoolAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'members', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardMember', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMajorPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakeAndDelegate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalMembersCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalStakedAmount', data: BytesLike): Result;
  }

  

  export interface BigViewTreasury extends BaseContract {
    
    connect(runner?: ContractRunner | null): BigViewTreasury;
    waitForDeployment(): Promise<this>;

    interface: BigViewTreasuryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    claimRewards: TypedContractMethod<
      [_tokenAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    devWallet: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getDashboardSummary: TypedContractMethod<
      [],
      [[bigint, bigint]],
      'view'
    >
    

    
    majorPoolAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    members: TypedContractMethod<
      [arg0: AddressLike, ],
      [[boolean, bigint] & {isMember: boolean, amount: bigint }],
      'view'
    >
    

    
    rewardMember: TypedContractMethod<
      [_member: AddressLike, _amount: BigNumberish, _token: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setMajorPool: TypedContractMethod<
      [_newPool: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    stakeAndDelegate: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    totalMembersCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalStakedAmount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'claimRewards'): TypedContractMethod<
      [_tokenAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'devWallet'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getDashboardSummary'): TypedContractMethod<
      [],
      [[bigint, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'majorPoolAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'members'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[boolean, bigint] & {isMember: boolean, amount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'rewardMember'): TypedContractMethod<
      [_member: AddressLike, _amount: BigNumberish, _token: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMajorPool'): TypedContractMethod<
      [_newPool: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stakeAndDelegate'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'totalMembersCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalStakedAmount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }