[project]
name = 'bigview-project'
description = ''
authors = []
telemetry = true
cache_dir = './.clarinet'

[[project.requirements]]
contract_id = 'ST35D3Y0P9RR8DC750D0X3BWBPSHJSYWY87ZZE9TE.bigview-treasury-v6'
[contracts.bigview-treasury-v6]
path = 'contracts/bigview-treasury-v6.clar'
clarity_version = 2
epoch = '2.5'

[contracts.pox-trait]
path = 'contracts/pox-trait.clar'
clarity_version = 2
epoch = '2.5'

[contracts.sip-010-trait]
path = 'contracts/sip-010-trait.clar'
clarity_version = 2
epoch = '2.5'
[repl.analysis]
passes = [
    'call_checker',
    'check_checker',
]

[repl.analysis.lint_groups]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = true
api_url = 'https://api.testnet.hiro.so'
