import { useState, useEffect } from "react";
import { StacksMainnet } from "@stacks/network";
import { callReadOnlyFunction, makeContractCall } from "@stacks/transactions";
import { uintCV, stringAsciiCV, boolCV } from "@stacks/transactions";

import StatusBadge from "./StatusBadge";
import DashboardButtons from "./DashboardButtons";
import DashboardData from "./DashboardData";

const CONTRACT_ADDRESS = "YOUR_CONTRACT_ADDRESS";
const CONTRACT_NAME = "bigview-treasury";

export default function Dashboard() {
  const [stake, setStake] = useState(0);
    const [reward, setReward] = useState(0);
      const [proposal, setProposal] = useState("None");
        const [votesFor, setVotesFor] = useState(0);
          const [votesAgainst, setVotesAgainst] = useState(0);
            const [message, setMessage] = useState("");

              function getWallet() {
                  return localStorage.getItem("userWallet");
                    }

                      // --- Read-only functions ---
                        async function fetchMySummary(wallet) {
                            if (!wallet) return;
                                const result = await callReadOnlyFunction({
                                      contractAddress: CONTRACT_ADDRESS,
                                            contractName: CONTRACT_NAME,
                                                  functionName: "my-summary",
                                                        functionArgs: [],
                                                              network: new StacksMainnet(),
                                                                    senderAddress: wallet,
                                                                        });
                                                                            setStake(result.value.my_stake || 0);
                                                                                setReward(result.value.my_reward || 0);
                                                                                  }

                                                                                    async function fetchProposal(id) {
                                                                                        const wallet = getWallet();
                                                                                            if (!wallet) return;
                                                                                                const result = await callReadOnlyFunction({
                                                                                                      contractAddress: CONTRACT_ADDRESS,
                                                                                                            contractName: CONTRACT_NAME,
                                                                                                                  functionName: "proposals",
                                                                                                                        functionArgs: [uintCV(id)],
                                                                                                                              network: new StacksMainnet(),
                                                                                                                                    senderAddress: wallet,
                                                                                                                                        });
                                                                                                                                            if (result.value) {
                                                                                                                                                  setProposal(result.value.description);
                                                                                                                                                        setVotesFor(result.value.votes_for);
                                                                                                                                                              setVotesAgainst(result.value.votes_against);
                                                                                                                                                                  }
                                                                                                                                                                    }

                                                                                                                                                                      useEffect(() => {
                                                                                                                                                                          const wallet = getWallet();
                                                                                                                                                                              if (wallet) {
                                                                                                                                                                                    fetchMySummary(wallet);
                                                                                                                                                                                          fetchProposal(1);
                                                                                                                                                                                              }
                                                                                                                                                                                                  const interval = setInterval(() => {
                                                                                                                                                                                                        const wallet = getWallet();
                                                                                                                                                                                                              if (wallet) {
                                                                                                                                                                                                                      fetchMySummary(wallet);
                                                                                                                                                                                                                              fetchProposal(1);
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                        }, 10000);
                                                                                                                                                                                                                                            return () => clearInterval(interval);
                                                                                                                                                                                                                                              }, []);

                                                                                                                                                                                                                                                // --- Transaction Handlers ---
                                                                                                                                                                                                                                                  async function handleStake() {
                                                                                                                                                                                                                                                      const wallet = getWallet();
                                                                                                                                                                                                                                                          const amount = uintCV(1000000);
                                                                                                                                                                                                                                                              const txOptions = {
                                                                                                                                                                                                                                                                    contractAddress: CONTRACT_ADDRESS,
                                                                                                                                                                                                                                                                          contractName: CONTRACT_NAME,
                                                                                                                                                                                                                                                                                functionName: "stake",
                                                                                                                                                                                                                                                                                      functionArgs: [amount],
                                                                                                                                                                                                                                                                                            senderKey: wallet,
                                                                                                                                                                                                                                                                                                  network: new StacksMainnet(),
                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                          const tx = await makeContractCall(txOptions);
                                                                                                                                                                                                                                                                                                              setMessage("Stake transaction submitted!");
                                                                                                                                                                                                                                                                                                                  console.log("Stake tx:", tx);
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                      async function handleUnstake() {
                                                                                                                                                                                                                                                                                                                          const wallet = getWallet();
                                                                                                                                                                                                                                                                                                                              const txOptions = {
                                                                                                                                                                                                                                                                                                                                    contractAddress: CONTRACT_ADDRESS,
                                                                                                                                                                                                                                                                                                                                          contractName: CONTRACT_NAME,
                                                                                                                                                                                                                                                                                                                                                functionName: "unstake",
                                                                                                                                                                                                                                                                                                                                                      functionArgs: [],
                                                                                                                                                                                                                                                                                                                                                            senderKey: wallet,
                                                                                                                                                                                                                                                                                                                                                                  network: new StacksMainnet(),
                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                          const tx = await makeContractCall(txOptions);
                                                                                                                                                                                                                                                                                                                                                                              setMessage("Unstake transaction submitted!");
                                                                                                                                                                                                                                                                                                                                                                                  console.log("Unstake tx:", tx);
                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                      async function handleClaim() {
                                                                                                                                                                                                                                                                                                                                                                                          const wallet = getWallet();
                                                                                                                                                                                                                                                                                                                                                                                              const txOptions = {
                                                                                                                                                                                                                                                                                                                                                                                                    contractAddress: CONTRACT_ADDRESS,
                                                                                                                                                                                                                                                                                                                                                                                                          contractName: CONTRACT_NAME,
                                                                                                                                                                                                                                                                                                                                                                                                                functionName: "claim-reward",
                                                                                                                                                                                                                                                                                                                                                                                                                      functionArgs: [],
                                                                                                                                                                                                                                                                                                                                                                                                                            senderKey: wallet,
                                                                                                                                                                                                                                                                                                                                                                                                                                  network: new StacksMainnet(),
                                                                                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                                                                                          const tx = await makeContractCall(txOptions);
                                                                                                                                                                                                                                                                                                                                                                                                                                              setMessage("Claim reward transaction submitted!");
                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log("Claim tx:", tx);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                      async function handleProposal() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                          const wallet = getWallet();
                                                                                                                                                                                                                                                                                                                                                                                                                                                              const desc = stringAsciiCV("Increase reward cycle length");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const txOptions = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        contractAddress: CONTRACT_ADDRESS,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              contractName: CONTRACT_NAME,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    functionName: "create-proposal",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          functionArgs: [desc],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                senderKey: wallet,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      network: new StacksMainnet(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const tx = await makeContractCall(txOptions);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setMessage("Proposal created!");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log("Proposal tx:", tx);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          async function handleVote() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const wallet = getWallet();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const proposalId = uintCV(1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const support = boolCV(true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const txOptions = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                contractAddress: CONTRACT_ADDRESS,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      contractName: CONTRACT_NAME,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            functionName: "vote",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  functionArgs: [proposalId, support],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        senderKey: wallet,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              network: new StacksMainnet(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const tx = await makeContractCall(txOptions);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setMessage("Vote submitted!");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log("Vote tx:", tx);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // --- UI ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div id="container">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <StatusBadge />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h1>BigView Dashboard</h1>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <DashboardButtons
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onStake={handleStake}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onUnstake={handleUnstake}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClaim={handleClaim}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onProposal={handleProposal}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onVote={handleVote}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3>Dashboard Data</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <DashboardData
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            stake={stake}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    reward={reward}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            proposal={proposal}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    votesFor={votesFor}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            votesAgainst={votesAgainst}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>Status: {message}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }