import { useState, useEffect } from "react";
import { StacksMocknet, StacksMainnet } from "@stacks/network";
import { callReadOnlyFunction, uintCV, stringAsciiCV, boolCV } from "@stacks/transactions";
import { openContractCall } from "@stacks/connect";

// --- CONFIGURATION ---
const CONTRACT_ADDRESS = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM";
const CONTRACT_NAME = "bigview-treasury";

// Auto-switch: If the .env says 'mainnet', use Mainnet. Otherwise, use Mocknet.
const network = process.env.NEXT_PUBLIC_NETWORK === 'mainnet' 
  ? new StacksMainnet() 
    : new StacksMocknet();

    export default function Dashboard({ user }) {
      const [stake, setStake] = useState(0);
        const [reward, setReward] = useState(0);
          const [proposal, setProposal] = useState("None");
            const [votesFor, setVotesFor] = useState(0);
              const [votesAgainst, setVotesAgainst] = useState(0);
                const [message, setMessage] = useState("Ready");

                  // Get user address from Privy object
                    const userAddress = user?.wallet?.address;

                      // --- Read-only functions (Viewing Data) ---
                        async function fetchMySummary() {
                            if (!userAddress) return;
                                try {
                                      const result = await callReadOnlyFunction({
                                              contractAddress: CONTRACT_ADDRESS,
                                                      contractName: CONTRACT_NAME,
                                                              functionName: "my-summary",
                                                                      functionArgs: [],
                                                                              network,
                                                                                      senderAddress: userAddress,
                                                                                            });
                                                                                                  // Adjusting based on standard Clarity response mapping
                                                                                                        setStake(result.value?.data?.['my-stake']?.value || 0);
                                                                                                              setReward(result.value?.data?.['my-reward']?.value || 0);
                                                                                                                  } catch (e) { console.error("Summary fetch error", e); }
                                                                                                                    }

                                                                                                                      async function fetchProposal(id) {
                                                                                                                          try {
                                                                                                                                const result = await callReadOnlyFunction({
                                                                                                                                        contractAddress: CONTRACT_ADDRESS,
                                                                                                                                                contractName: CONTRACT_NAME,
                                                                                                                                                        functionName: "proposals",
                                                                                                                                                                functionArgs: [uintCV(id)],
                                                                                                                                                                        network,
                                                                                                                                                                                senderAddress: userAddress || CONTRACT_ADDRESS,
                                                                                                                                                                                      });
                                                                                                                                                                                            if (result.value) {
                                                                                                                                                                                                    setProposal(result.value.data.description.data);
                                                                                                                                                                                                            setVotesFor(Number(result.value.data['votes-for'].value));
                                                                                                                                                                                                                    setVotesAgainst(Number(result.value.data['votes-against'].value));
                                                                                                                                                                                                                          }
                                                                                                                                                                                                                              } catch (e) { console.error("Proposal fetch error", e); }
                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                  useEffect(() => {
                                                                                                                                                                                                                                      fetchMySummary();
                                                                                                                                                                                                                                          fetchProposal(1);
                                                                                                                                                                                                                                              const interval = setInterval(() => {
                                                                                                                                                                                                                                                    fetchMySummary();
                                                                                                                                                                                                                                                          fetchProposal(1);
                                                                                                                                                                                                                                                              }, 15000);
                                                                                                                                                                                                                                                                  return () => clearInterval(interval);
                                                                                                                                                                                                                                                                    }, [userAddress]);

                                                                                                                                                                                                                                                                      // --- Smart Contract Call Helper (The Popup Logic) ---
                                                                                                                                                                                                                                                                        const executeContractCall = async (functionName, functionArgs, successMsg) => {
                                                                                                                                                                                                                                                                            const options = {
                                                                                                                                                                                                                                                                                  contractAddress: CONTRACT_ADDRESS,
                                                                                                                                                                                                                                                                                        contractName: CONTRACT_NAME,
                                                                                                                                                                                                                                                                                              functionName,
                                                                                                                                                                                                                                                                                                    functionArgs,
                                                                                                                                                                                                                                                                                                          network,
                                                                                                                                                                                                                                                                                                                onFinish: (data) => {
                                                                                                                                                                                                                                                                                                                        setMessage(`${successMsg}! TX ID: ${data.txId.substring(0, 10)}...`);
                                                                                                                                                                                                                                                                                                                                console.log("Transaction Result:", data);
                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                            onCancel: () => setMessage("Transaction cancelled."),
                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                    await openContractCall(options);
                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                        // --- Handlers for your Buttons ---
                                                                                                                                                                                                                                                                                                                                                          const handleStake = () => executeContractCall("stake", [uintCV(1000000)], "Staked 1 STX");
                                                                                                                                                                                                                                                                                                                                                            const handleUnstake = () => executeContractCall("unstake", [], "Unstaked successfully");
                                                                                                                                                                                                                                                                                                                                                              const handleClaim = () => executeContractCall("claim-reward", [], "Reward claimed");
                                                                                                                                                                                                                                                                                                                                                                const handleProposal = () => executeContractCall("create-proposal", [stringAsciiCV("New Governance Rule")], "Proposal Created");
                                                                                                                                                                                                                                                                                                                                                                  const handleVote = () => executeContractCall("vote", [uintCV(1), boolCV(true)], "Voted YES");

                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                        <div style={{ padding: "20px", fontFamily: "sans-serif" }}>
                                                                                                                                                                                                                                                                                                                                                                              <h1>BigView Dashboard</h1>
                                                                                                                                                                                                                                                                                                                                                                                    <p>Logged in as: <strong>{userAddress}</strong></p>
                                                                                                                                                                                                                                                                                                                                                                                          <hr />
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ marginBottom: "20px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                              <button onClick={handleStake}>Stake 1 STX</button>
                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={handleUnstake}>Unstake</button>
                                                                                                                                                                                                                                                                                                                                                                                                                              <button onClick={handleClaim}>Claim Reward</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={handleProposal}>New Proposal</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <button onClick={handleVote}>Vote YES on #1</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ background: "#f4f4f4", padding: "15px", borderRadius: "8px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3>Blockchain Data</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>My Stake: {stake} micro-STX</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>My Reward: {reward} micro-STX</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>Active Proposal: {proposal}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>Votes: ✅ {votesFor} | ❌ {votesAgainst}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p style={{ color: "blue" }}>Status: {message}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }