import React, { useState, useEffect } from "react";
import { StacksNetworks } from "@stacks/network"; 
import * as StacksTransactions from "@stacks/transactions";
import { openContractCall } from "@stacks/connect";

// --- CONFIGURATION ---
// I've added your deployed contract details here
const CONTRACT_ADDRESS = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM"; 
const CONTRACT_NAME = "bigview-treasury";
const network = StacksNetworks.testnet; 

export default function Dashboard() {
  const [stake, setStake] = useState(0);
    const [reward, setReward] = useState(0);
      const [message, setMessage] = useState("Ready");

        // PASTE YOUR REAL TESTNET ADDRESS HERE
          const userAddress = "ST414MTX2NQ4MVMRE2J9CQATKDEWVXT3DA96XHHA";

            async function fetchMySummary() {
                if (!userAddress) return;
                    setMessage("Fetching real contract data...");
                        try {
                              const result = await StacksTransactions.fetchCallReadOnlyFunction({
                                      contractAddress: CONTRACT_ADDRESS,
                                              contractName: CONTRACT_NAME,
                                                      functionName: "my-summary",
                                                              functionArgs: [],
                                                                      network,
                                                                              senderAddress: userAddress,
                                                                                    });
                                                                                          
                                                                                                // This will print the actual data from your deployed contract!
                                                                                                      console.log("REAL CONTRACT DATA:", result);
                                                                                                            setMessage("Data Loaded from Testnet");
                                                                                                                  
                                                                                                                        // If you want to see the numbers in the UI, we'd parse 'result' here
                                                                                                                            } catch (e) { 
                                                                                                                                  console.error("Contract Fetch Error:", e);
                                                                                                                                        setMessage("Error fetching from contract.");
                                                                                                                                            }
                                                                                                                                              }

                                                                                                                                                useEffect(() => {
                                                                                                                                                    fetchMySummary();
                                                                                                                                                      }, []);

                                                                                                                                                        const executeContractCall = async (functionName, functionArgs, successMsg) => {
                                                                                                                                                            setMessage(`Calling ${functionName}...`);

                                                                                                                                                                const options = {
                                                                                                                                                                      contractAddress: CONTRACT_ADDRESS,
                                                                                                                                                                            contractName: CONTRACT_NAME,
                                                                                                                                                                                  functionName,
                                                                                                                                                                                        functionArgs,
                                                                                                                                                                                              network,
                                                                                                                                                                                                    onFinish: (data) => {
                                                                                                                                                                                                            setMessage(`${successMsg}! TX: ${data.txId.substring(0, 10)}`);
                                                                                                                                                                                                                  },
                                                                                                                                                                                                                        onCancel: () => setMessage("Transaction cancelled."),
                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                // This will trigger your Leather/Xverse wallet if you have it
                                                                                                                                                                                                                                    if (window.StacksProvider || window.LeatherProvider) {
                                                                                                                                                                                                                                          await openContractCall(options);
                                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                                    setMessage("Wallet not found. Use a Stacks-compatible browser.");
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                            const handleStake = () => {
                                                                                                                                                                                                                                                                const amount = StacksTransactions.uintCV(1000000); // 1 STX
                                                                                                                                                                                                                                                                    executeContractCall("stake", [amount], "Stake successful");
                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                            <div style={{ padding: "30px", textAlign: "center", fontFamily: "sans-serif", maxWidth: "450px", margin: "auto" }}>
                                                                                                                                                                                                                                                                                  <h2 style={{ color: "#333" }}>BigView Treasury</h2>
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                              <div style={{ background: "#5546FF", color: "white", padding: "15px", borderRadius: "12px", marginBottom: "20px" }}>
                                                                                                                                                                                                                                                                                                      <p style={{ margin: 0, fontSize: "12px" }}>Contract Address:</p>
                                                                                                                                                                                                                                                                                                              <p style={{ margin: "5px 0", fontWeight: "bold", fontSize: "11px" }}>{CONTRACT_ADDRESS}</p>
                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                          <button 
                                                                                                                                                                                                                                                                                                                                  style={{ 
                                                                                                                                                                                                                                                                                                                                            padding: "18px", 
                                                                                                                                                                                                                                                                                                                                                      borderRadius: "12px", 
                                                                                                                                                                                                                                                                                                                                                                backgroundColor: "#000", 
                                                                                                                                                                                                                                                                                                                                                                          color: "white", 
                                                                                                                                                                                                                                                                                                                                                                                    border: "none", 
                                                                                                                                                                                                                                                                                                                                                                                              width: "100%", 
                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: "16px", 
                                                                                                                                                                                                                                                                                                                                                                                                                  fontWeight: "bold", 
                                                                                                                                                                                                                                                                                                                                                                                                                            cursor: "pointer" 
                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={handleStake}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                          Stake 1 STX
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ background: "#f8f9fa", padding: "20px", borderRadius: "15px", textAlign: "left", marginTop: "20px", border: "1px solid #eee" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p><strong>Network:</strong> Testnet</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p><strong>Status:</strong> {message}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }