import React, { useState, useEffect } from "react";
import { STACKS_TESTNET } from "@stacks/network"; 
import * as StacksTransactions from "@stacks/transactions";
import { openContractCall } from "@stacks/connect";
import { TestsNotFoundError } from "vitest/node";
import DashboardData from '../components/DashboardData';
import StatusBadge from '../components/StatusBadge';
import DashboardButtons from '../components/DashboardButtons';

// --- CONFIGURATION ---
// I've added your deployed contract details here
const CONTRACT_ADDRESS = "ST414MTX2NQ4MVMRE2J9CQATKDEWVXT3DA96XHHA";
const CONTRACT_NAME = "bigview-treasury";
const network = 'testnet';

export default function Dashboard() {
  const [stake, setStake] = useState(0);
    const [reward, setReward] = useState(0);
      const [message, setMessage] = useState("Ready");

        // PASTE YOUR REAL TESTNET ADDRESS HERE
          const userAddress = "ST35D3Y0P9RR8DC750D0X3BWBPSHJSYWY87ZZE9TE";

            async function fetchMySummary() {
                if (!userAddress) return;
                    setMessage("Fetching real contract data...");
                        try {
                              const result = await StacksTransactions.fetchCallReadOnlyFunction({
                                      contractAddress: CONTRACT_ADDRESS,
                                              contractName: CONTRACT_NAME,
                                                      functionName: "dashboard-summary",
                                                              functionArgs: [],
                                                                      network,
                                                                              senderAddress: userAddress,
                                                                                    });
                                                                                          
                                                                                                // This will print the actual data from your deployed contract!
                                                                                                      console.log("REAL CONTRACT DATA:", result);
                                                                                                            setMessage("Data Loaded from Testnet");
                                                                                                                  
                                                                                                                        // If you want to see the numbers in the UI, we'd parse 'result' here
                                                                                                                            } catch (e) { 
                                                                                                                                  console.error("Contract Fetch Error:", e);
                                                                                                                                        setMessage("Error fetching from contract.");
                                                                                                                                            }
                                                                                                                                              }

                                                                                                                                                useEffect(() => {
                                                                                                                                                    fetchMySummary();
                                                                                                                                                      }, []);

                                                                                                                                                        const executeContractCall = async (functionName, functionArgs, successMsg) => {
                                                                                                                                                            setMessage(`Calling ${functionName}...`);

                                                                                                                                                                const options = {
                                                                                                                                                                      contractAddress: CONTRACT_ADDRESS,
                                                                                                                                                                            contractName: CONTRACT_NAME,
                                                                                                                                                                                  functionName,
                                                                                                                                                                                        functionArgs,
                                                                                                                                                                                              network,
                                                                                                                                                                                                    onFinish: (data) => {
                                                                                                                                                                                                            setMessage(`${successMsg}! TX: ${data.txId.substring(0, 10)}`);
                                                                                                                                                                                                                  },
                                                                                                                                                                                                                        onCancel: () => setMessage("Transaction cancelled."),
                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                // This will trigger your Leather/Xverse wallet if you have it
                                                                                                                                                                                                                                    if (window.StacksProvider || window.LeatherProvider) {
                                                                                                                                                                                                                                          await openContractCall(options);
                                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                                    setMessage("Wallet not found. Use a Stacks-compatible browser.");
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                            const handleStake = () => {
                                                                                                                                                                                                                                                                const amount = StacksTransactions.uintCV(1000000); // 1 STX
                                                                                                                                                                                                                                                                    executeContractCall("stake", [amount], "Stake successful");
                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                              /* This 'dashboard' class connects to your globals.css */
                                                                                                                                                                                                                                                                                <div className="min-h-screen bg-[#f8fafc] flex flex-col items-center py-10">
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                        {/* THE MAIN CONTAINER: This centers everything so it doesn't look 'anyhow' */}
                                                                                                                                                                                                                                                                                            <div className="w-full max-w-4xl px-4 flex flex-col gap-6">
                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                        {/* 1. HEADER COMPONENT */}
                                                                                                                                                                                                                                                                                                              <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100 flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                      <h1 className="text-xl font-bold text-[#002D72]">BIGVIEW TREASURY</h1>
                                                                                                                                                                                                                                                                                                                              {/* CALL YOUR COMPONENT HERE */}
                                                                                                                                                                                                                                                                                                                                      <StatusBadge /> 
                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                  {/* 2. DATA COMPONENT */}
                                                                                                                                                                                                                                                                                                                                                        <div className="bg-white p-8 rounded-3xl shadow-sm border border-slate-100">
                                                                                                                                                                                                                                                                                                                                                                {/* CALL YOUR COMPONENT HERE - Pass the data as props */}
                                                                                                                                                                                                                                                                                                                                                                        <DashboardData stake={stake} reward={reward} />
                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                    {/* 3. BUTTONS COMPONENT */}
                                                                                                                                                                                                                                                                                                                                                                                          <div className="bg-white p-8 rounded-3xl shadow-sm border border-slate-100">
                                                                                                                                                                                                                                                                                                                                                                                                  {/* CALL YOUR COMPONENT HERE - Pass your function */}
                                                                                                                                                                                                                                                                                                                                                                                                          <DashboardButtons onStake={handleStake} />
                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                      <footer className="text-center text-[10px] text-slate-400 font-mono mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                              CONNECTED ADDRESS: {userAddress?.slice(0, 10)}...
                                                                                                                                                                                                                                                                                                                                                                                                                                    </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                    

                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                        

                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                        

                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                              

                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                

                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                            

                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                            

                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                          

                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                

                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                          

                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                      